#!/bin/sh

dir=$(dirname $(readlink -f $0))
cd "$dir"

which docker >/dev/null 2>&1
if [ $? != 0 ]
then
    echo "Docker not found"
    exit 1
fi


echo "Building Docker image..."
cd docker && ./build || exit 1
cd "$dir"

specdir=$dir/install
if [ ! -d $specdir ]
then
    echo "Extracting SPEC..."
    if [ ! -f $dir/spec2k6.tar.gz ]
    then
        echo "Can't find spec2k6.tar.gz"
        exit 1
    fi
    tar xf $dir/spec2k6.tar.gz
    cp config/* $specdir/config/
fi

echo "Launching SPEC..."
docker/run --noreportable --tune=all $@ all
