#!/bin/sh

dir=$(dirname $(readlink -f $0))
cd "$dir"

which docker >/dev/null 2>&1
if [ $? != 0 ]
then
    echo "Docker not found"
    exit 1
fi


echo "Building Docker image..."
cd docker && ./build || exit 1
cd "$dir"

specdir=$dir/install
if [ ! -d $specdir ]
then
    echo "Extracting SPEC..."
    if [ ! -f $dir/spec2k6.tar.gz ]
    then
        echo "Can't find spec2k6.tar.gz"
        exit 1
    fi
    checksum=$(sha256sum $dir/spec2k6.tar.gz | cut -d " " -f1)
    if [ "$checksum" != "eb6c81181f14204aa23910c8136382281279ff9c6d93a47fa05290becc35d402" ]
    then
        echo "Wrong checksum"
        exit 1
    fi
    tar xf $dir/spec2k6.tar.gz
    cp config/* $specdir/config/
fi

echo "Launching SPEC..."
docker/run --noreportable --tune=all $@ all
